datasets: 
    wikitext103: en
    chinese_documents: zh

models:
    copyisallyouneed: 
        model_name: Copyisallyouneed
        dataset_name: CopyisallyouneedWikitext103V2Dataset
    gpt2:
        model_name: GPT2Baseline
        dataset_name: GPT2Dataset
    knnlm:
        model_name: KNNLMBaseline
        dataset_name: KNNLMInferenceDataset


# ========= Global configuration ========== #
# root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed
root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed
# data_root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed/data/wikitext103_1024
data_root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed/data/wikitext103_1024
version: 2003
# ========= Global configuration ========== #
